export const SET_AREA_LINES = 'SET_AREA_LINES';
export const SET_AREA_LINE_WIDTH = 'SET_AREA_LINE_WIDTH';
export const SET_AREA_LINE_OPACITY = 'SET_AREA_LINE_OPACITY';
export const SET_AREA_LINE_CURVE = 'SET_AREA_LINE_CURVE';
export const SET_AREA_LINE_DASHED = 'SET_AREA_LINE_DASHED';
