export const SET_DATA_LABELS = 'SET_DATA_LABELS';
export const SET_DATA_LABELS_COLOR = 'SET_DATA_LABELS_COLOR';
export const SET_DATA_LABELS_SIZE = 'SET_DATA_LABELS_SIZE';
export const SET_DATA_LABELS_FORMAT = 'SET_DATA_LABELS_FORMAT';
