export const SET_LINE_DOTS = 'SET_LINE_DOTS';
export const SET_LINE_DOT_SHAPE = 'SET_LINE_DOT_SHAPE';
export const SET_LINE_DOT_SIZE = 'SET_LINE_DOT_SIZE';
export const SET_LINE_DOTS_HOLLOW = 'SET_LINE_DOTS_HOLLOW';
