export const SET_FACET_COLUMNS = 'SET_FACET_COLUMNS';
export const SET_FACET_SPACING = 'SET_FACET_SPACING';
export const SET_FACET_XAXIS = 'SET_FACET_XAXIS';
export const SET_FACET_YAXIS = 'SET_FACET_YAXIS';
