export const SET_LEGEND_LABEL_POSITION = 'SET_LEGEND_LABEL_POSITION';
export const SET_LEGEND_LABEL_BASELINE = 'SET_LEGEND_LABEL_BASELINE';
export const SET_LEGEND_LABEL_COLOR = 'SET_LEGEND_LABEL_COLOR';
