export const SET_LEGEND_POSITION = 'SET_LEGEND_POSITION';
export const SET_LEGEND_TITLE = 'SET_LEGEND_TITLE';
export const SET_LEGEND_BACKGROUND = 'SET_LEGEND_BACKGROUND';
export const SET_LEGEND_SYMBOL = 'SET_LEGEND_SYMBOL';
export const SET_LEGEND_SYMBOL_SIZE = 'SET_LEGEND_SYMBOL_SIZE';
