export const SET_LINE_WIDTH = 'SET_SET_LINE_WIDTH';
export const SET_LINE_OPACITY = 'SET_LINE_OPACITY';
export const SET_LINE_CURVE = 'SET_LINE_CURVE';
export const SET_LINE_DASHED = 'SET_LINE_DASHED';
