export const SET_PIE_DATA_LABELS = 'SET_PIE_DATA_LABELS';
export const SET_PIE_DATA_LABELS_SIZE = 'SET_PIE_DATA_LABELS_SIZE';
export const SET_PIE_DATA_LABELS_POSITION = 'SET_PIE_DATA_LABELS_POSITION';
