export const SET_PIE_OUTER_RADIUS = 'SET_PIE_OUTER_RADIUS';
export const SET_PIE_INNER_RADIUS = 'SET_PIE_INNER_RADIUS';
export const SET_PIE_CORNER_RADIUS = 'SET_PIE_CORNER_RADIUS';
export const SET_PIE_PADDING_ANGLE = 'SET_PIE_PADDING_ANGLE';
