export const SET_XAXIS_TITLE = 'SET_XAXIS_TITLE';
export const SET_XAXIS_POSITION = 'SET_XAXIS_POSITION';
export const SET_XAXIS_LABEL_FORMAT = 'SET_XAXIS_LABEL_FORMAT';
export const SET_XAXIS_LABEL_COLOR = 'SET_XAXIS_LABEL_COLOR';
