export const SET_YAXIS_TITLE = 'SET_YAXIS_TITLE';
export const SET_YAXIS_POSITION = 'SET_YAXIS_POSITION';
export const SET_YAXIS_LABEL_FORMAT = 'SET_YAXIS_LABEL_FORMAT';
export const SET_YAXIS_LABEL_COLOR = 'SET_YAXIS_LABEL_COLOR';
